#############################################################################
# Makefile for building: ProyectoIA1.app/Contents/MacOS/ProyectoIA1
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  ProyectoIA1.pro
# Template: app
# Command: /Users/diegoruiz/Qt/5.6/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile ProyectoIA1.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -std=gnu++11 -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.6/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.6/clang_64/mkspecs/macx-clang -F/Users/diegoruiz/Qt/5.6/clang_64/lib
QMAKE         = /Users/diegoruiz/Qt/5.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ProyectoIA11.0.0
DISTDIR = /Users/diegoruiz/Documents/ProyectoIA1/ProyectoIA1/.tmp/ProyectoIA11.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/diegoruiz/Qt/5.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/diegoruiz/Qt/5.6/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		duthread.cpp \
		minmax.cpp \
		nodo.cpp moc_mainwindow.cpp \
		moc_duthread.cpp
OBJECTS       = main.o \
		mainwindow.o \
		duthread.o \
		minmax.o \
		nodo.o \
		moc_mainwindow.o \
		moc_duthread.o
DIST          = images/mario_left.png \
		images/mario_right.png \
		mario.png \
		file.txt \
		prueba11.txt \
		images/chess-black.png \
		images/chess-white.png \
		images/fruit.png \
		../../../Qt/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.6/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.6/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.6/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.6/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/lex.prf \
		ProyectoIA1.pro mainwindow.hpp \
		duthread.hpp \
		minmax.hpp \
		nodo.hpp main.cpp \
		mainwindow.cpp \
		duthread.cpp \
		minmax.cpp \
		nodo.cpp
QMAKE_TARGET  = ProyectoIA1
DESTDIR       = 
TARGET        = ProyectoIA1.app/Contents/MacOS/ProyectoIA1


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d ProyectoIA1.app/Contents/MacOS/ || mkdir -p ProyectoIA1.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ProyectoIA1.pro ../../../Qt/5.6/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.6/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.6/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.6/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.6/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.6/clang_64/mkspecs/features/lex.prf \
		ProyectoIA1.pro \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.6/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile ProyectoIA1.pro
../../../Qt/5.6/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.6/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.6/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.6/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.6/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.6/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.6/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.6/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.6/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.6/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.6/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.6/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.6/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.6/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.6/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.6/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.6/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.6/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.6/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.6/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.6/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.6/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.6/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.6/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.6/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.6/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.6/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.6/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.6/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.6/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.6/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.6/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.6/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.6/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.6/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.6/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.6/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.6/clang_64/mkspecs/features/lex.prf:
ProyectoIA1.pro:
../../../Qt/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.6/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile ProyectoIA1.pro

qmake_all: FORCE

ProyectoIA1.app/Contents/PkgInfo: 
	@test -d ProyectoIA1.app/Contents || mkdir -p ProyectoIA1.app/Contents
	@$(DEL_FILE) ProyectoIA1.app/Contents/PkgInfo
	@echo "APPL????" > ProyectoIA1.app/Contents/PkgInfo
ProyectoIA1.app/Contents/Resources/empty.lproj: 
	@test -d ProyectoIA1.app/Contents/Resources || mkdir -p ProyectoIA1.app/Contents/Resources
	@touch ProyectoIA1.app/Contents/Resources/empty.lproj
	
ProyectoIA1.app/Contents/Info.plist: 
	@test -d ProyectoIA1.app/Contents || mkdir -p ProyectoIA1.app/Contents
	@$(DEL_FILE) ProyectoIA1.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.ProyectoIA1,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,ProyectoIA1,g" -e "s,@LIBRARY@,ProyectoIA1,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.6/clang_64/mkspecs/macx-clang/Info.plist.app >ProyectoIA1.app/Contents/Info.plist

all: Makefile \
		ProyectoIA1.app/Contents/PkgInfo \
		ProyectoIA1.app/Contents/Resources/empty.lproj \
		ProyectoIA1.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.hpp duthread.hpp minmax.hpp nodo.hpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp duthread.cpp minmax.cpp nodo.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r ProyectoIA1.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_duthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_duthread.cpp
moc_mainwindow.cpp: ../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		duthread.hpp \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qthread.h \
		minmax.hpp \
		nodo.hpp \
		mainwindow.hpp
	/Users/diegoruiz/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/diegoruiz/Qt/5.6/clang_64/mkspecs/macx-clang -I/Users/diegoruiz/Documents/ProyectoIA1/ProyectoIA1 -I/Users/diegoruiz/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/diegoruiz/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/diegoruiz/Qt/5.6/clang_64/lib/QtCore.framework/Headers -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -F/Users/diegoruiz/Qt/5.6/clang_64/lib mainwindow.hpp -o moc_mainwindow.cpp

moc_duthread.cpp: ../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qthread.h \
		duthread.hpp
	/Users/diegoruiz/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/diegoruiz/Qt/5.6/clang_64/mkspecs/macx-clang -I/Users/diegoruiz/Documents/ProyectoIA1/ProyectoIA1 -I/Users/diegoruiz/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/diegoruiz/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/diegoruiz/Qt/5.6/clang_64/lib/QtCore.framework/Headers -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -F/Users/diegoruiz/Qt/5.6/clang_64/lib duthread.hpp -o moc_duthread.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/diegoruiz/Qt/5.6/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.hpp \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		duthread.hpp \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qthread.h \
		minmax.hpp \
		nodo.hpp \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.hpp \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		duthread.hpp \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qthread.h \
		minmax.hpp \
		nodo.hpp \
		ui_mainwindow.h \
		ui_form.h \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

duthread.o: duthread.cpp duthread.hpp \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.6/clang_64/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o duthread.o duthread.cpp

minmax.o: minmax.cpp minmax.hpp \
		nodo.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minmax.o minmax.cpp

nodo.o: nodo.cpp nodo.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nodo.o nodo.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_duthread.o: moc_duthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_duthread.o moc_duthread.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

